fix: calling of secret was rectified

diff --git a/.github/workflows/ci-user-service.yml b/.github/workflows/ci-user-service.yml
--- a/.github/workflows/ci-user-service.yml
+++ b/.github/workflows/ci-user-service.yml
@@ -103,13 +103,13 @@ jobs:
     timeout-minutes: 20
     env:
       SERVICE_NAME: "user-service"
-      DAST_TARGET_URL: ${{ vars.DAST_TARGET_URL }}
+      DAST_TARGET_URL: ${{ secrets.DAST_TARGET_URL }}
     steps:
       - name: Validate DAST target
         shell: bash
         run: |
           if [ -z "${{ env.DAST_TARGET_URL }}" ]; then
-            echo "Repository variable DAST_TARGET_URL is required (example: https://fitforge360.in)." >&2
+            echo "Repository variable DAST_TARGET_URL is required (example: http://fitforge360.in)." >&2
             # Adding this as a secret in for the repo
             exit 1
           fi
